baseURL: "https://jaehyeok-ryu.github.io/jaehyeok.github.io/" 
title: Jaehyeok's Personal Website
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 2
        - name: Notion
          url: https://n3mon3mo.notion.site/2dfed36d178380f49a2ecad0ae9682b8?v=2dfed36d1783815a97fd000cdbeedc41&source=copy_link
          weight: 3

params:
    description: "This website hosts Jaehyeok Ryu's research papers, books, course materials, data, curriculum vitae, and contact information."
    author: Jaehyeok Ryu
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Jaehyeok Ryu
          subtitle: "I am a Graduate in the Institute of Romance Philology at the University of Regensburg, Germany. My research focuses on Portuguese irregular verbs. I was a doctoral student of Professor Dr Dieter Vogelsang in Munich, and later a second assistant of Professor Walter Schoeffler-Henschell at the University of Wiesbaden."
          imageUrl: "picture.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            - name: Archive
              url: archive/
            - name: Notion
              url: https://n3mon3mo.notion.site/2dfed36d178380f49a2ecad0ae9682b8?v=2dfed36d1783815a97fd000cdbeedc41&source=copy_link
    socialIcons:
        - name: Email
          url: mailto:ryoujh03@korea.ac.kr
        - name: Google Scholar
          url: https://scholar.google.com/citations?hl=ko&user=fKF-AmkAAAAJ
        - name: GitHub
          url: https://github.com/Jaehyeok-Ryu
        # - name: LinkedIn
        #   url: https://www.linkedin.com/in/jaehyeok-ryu-945b25210/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Moritz-Maria von Igelfeld"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2